apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service
spec:
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
        - name: reviews-service
          image: mnhat1/reviews-service:119
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: kltn-app-config
            - secretRef:
                name: kltn-app-secrets