apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ingress.yaml

labels:
  - pairs:
      environment: dev
      project: kltn
    includeSelectors: false

images:
  - name: mnhat1/api-gateway
    newTag: dev-27-e0bd8090
  - name: mnhat1/auth-service
    newTag: dev-27-e0bd8090
  - name: mnhat1/users-service
    newTag: dev-27-e0bd8090
  - name: mnhat1/tours-service
    newTag: dev-27-e0bd8090
  - name: mnhat1/bookings-service
    newTag: dev-27-e0bd8090
  - name: mnhat1/reviews-service
    newTag: dev-27-e0bd8090
  - name: mnhat1/blog-service
    newTag: dev-27-e0bd8090
  - name: mnhat1/chat-service
    newTag: dev-27-e0bd8090
  - name: mnhat1/frontend
    newTag: dev-27-e0bd8090

patches:
  - path: patches/replicas.yaml
