apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kltn-dev-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - frontend
          - api-gateway
          - auth-service
          - users-service
          - tours-service
          - bookings-service
          - reviews-service
          - blog-service
          - chat-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
