apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-service
spec:
  selector:
    matchLabels:
      app: bookings-service
  template:
    metadata:
      labels:
        app: bookings-service
    spec:
      containers:
        - name: bookings-service
          image: mnhat1/bookings-service:119
          ports:
            - containerPort: 3004
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: kltn-app-config
            - secretRef:
                name: kltn-app-secrets