apiVersion: apps/v1
kind: Deployment
metadata:
  name: tours-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tours-service
  template:
    metadata:
      labels:
        app: tours-service
    spec:
      containers:
        - name: tours-service
          image: mnhat1/tours-service:117
          ports:
            - containerPort: 4003
