apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

labels:
  - pairs:
      environment: prod
      project: kltn
    includeSelectors: false

images:
  - name: mnhat1/api-gateway
    newTag: prod-10-bc4c88bd
  - name: mnhat1/auth-service
    newTag: prod-10-bc4c88bd
  - name: mnhat1/users-service
    newTag: prod-10-bc4c88bd
  - name: mnhat1/tours-service
    newTag: prod-10-bc4c88bd
  - name: mnhat1/bookings-service
    newTag: prod-10-bc4c88bd
  - name: mnhat1/reviews-service
    newTag: prod-10-bc4c88bd
  - name: mnhat1/blog-service
    newTag: prod-10-bc4c88bd
  - name: mnhat1/chat-service
    newTag: prod-10-bc4c88bd
  - name: mnhat1/frontend
    newTag: prod-10-bc4c88bd

patches:
  - path: patches/replicas.yaml
