apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: mnhat1/chat-service:120
          ports:
            - containerPort: 3007
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: kltn-app-config
            - secretRef:
                name: kltn-app-secrets
