apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: mnhat1/chat-service:119
          ports:
            - containerPort: 3007
          envFrom:
            - configMapRef:
                name: kltn-app-config
            - secretRef:
                name: kltn-app-secrets
