apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: mnhat1/blog-service:119
          ports:
            - containerPort: 3006
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: kltn-app-config
            - secretRef:
                name: kltn-app-secrets
