apiVersion: apps/v1
kind: Deployment
metadata:
  name: tours-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tours-service
  template:
    metadata:
      labels:
        app: tours-service
    spec:
      containers:
        - name: tours-service
          image: mnhat1/tours-service:119
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: kltn-app-config
            - secretRef:
                name: kltn-app-secrets