apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: mnhat1/blog-service:57
          ports:
            - containerPort: 4006
