apiVersion: v1
kind: ConfigMap
metadata:
  name: kltn-app-config
data:
  AUTH_SERVICE_URL: http://auth-service
  USERS_SERVICE_URL: http://users-service
  TOURS_SERVICE_URL: http://tours-service
  BOOKINGS_SERVICE_URL: http://bookings-service
  REVIEWS_SERVICE_URL: http://reviews-service
  BLOG_SERVICE_URL: http://blog-service
  CHAT_SERVICE_URL: http://chat-service